### ISSUE TITLE
[BUG] Unexpected encoding in url.path for request completed

### ISSUE THREAD

**Issue by fredmaggiowski** [mia-platform/glogger#10]
## Describe the bug

Unexpected `&` encoing for path query parameters

The `request completed` log presents encoded `&` when logging `url.path` key, below follows an example log from a service

```
{"host":{"hostname":"myservice","forwardedHost":"forwardedhost"},"http":{"request":{"method":"GET","userAgent":{"original":"got/9.6.0 (https://github.com/sindresorhus/got)"}},"response":{"statusCode":200,"body":{"bytes":2}}},"level":30,"msg":"request completed","reqId":"xyz","responseTime":78,"time":1608556458,"url":{"path":"/users?_l=50\u0026_sk=0\u0026username=fe*\u0026email=fe*"}}
```

## How To Reproduce

Invoke a path using query parameters for an API that uses glogger middleware

## Expected behavior

Proper information encoding

## System Info

- Go Version 1.15.2

**Comment by davidebianchi** [comment]
If we want to support the correct encoding, it is quite simple: we should set `SetEscapeHTML` to true in json marshalling (https://golang.org/pkg/encoding/json/#Encoder.SetEscapeHTML).

It could be a safety problem if not handled in render view.

**Comment by fredmaggiowski** [comment]
Yes, that sounds good these are application logs hence I don't think we need not worry about rendering html
